import type {
  Doctor,
  Department,
  HealthPackage,
  BlogPost,
  GalleryItem,
  Testimonial,
  ContactInquiry,
  OnlineAppointment,
} from './types';

export const mockDepartments: Department[] = [
  {
    id: 'dept-1',
    name: 'Cardiology & Cardiac Surgery',
    code: 'CARD',
    headDoctor: 'Dr. Vikram Reddy, MD, DM',
    opdRoom: 'OPD-101',
    totalBeds: 45,
    description: 'Comprehensive 24/7 cardiac emergency care, interventional cardiology, TAVI, and minimally invasive bypass surgeries.',
    services: ['24/7 Cath Lab & Angioplasty', 'Coronary Artery Bypass (CABG)', 'Pacemaker Implantation', '3D Echocardiography', 'Heart Failure Clinic'],
  },
  {
    id: 'dept-2',
    name: 'Neurology & Neurosurgery',
    code: 'NEUR',
    headDoctor: 'Dr. Ananya Swaminathan, M.Ch',
    opdRoom: 'OPD-104',
    totalBeds: 30,
    description: 'Advanced brain and spine surgery, stroke resuscitation unit, epilepsy care, and neuro-critical monitoring.',
    services: ['Micro-Neurosurgery', 'Endoscopic Brain Surgery', 'Spine Stabilization', 'Stroke Emergency Unit', 'Neuro-Rehabilitation'],
  },
  {
    id: 'dept-3',
    name: 'Orthopedics & Joint Replacement',
    code: 'ORTH',
    headDoctor: 'Dr. Rajeshwar Rao, MS (Ortho)',
    opdRoom: 'OPD-202',
    totalBeds: 50,
    description: 'Robotic knee and hip replacement, complex trauma surgery, sports medicine, and arthroscopy.',
    services: ['Robotic Total Knee Replacement', 'Hip Resurfacing & Revision', 'Arthroscopic Ligament Repair', 'Polytrauma Care', 'Physiotherapy Suite'],
  },
  {
    id: 'dept-4',
    name: 'Emergency & Trauma Resuscitation',
    code: 'EMER',
    headDoctor: 'Dr. Sameer Khan, MD (EM)',
    opdRoom: 'EMR-BAY-01',
    totalBeds: 25,
    description: 'Round-the-clock level 1 trauma resuscitation, cardiac emergency bay, and ALS ambulance fleet.',
    services: ['Trauma Resuscitation', 'Advanced Ventilator Support', 'Poison & Toxicology Care', 'Medico-Legal Registration', 'ALS Ambulance Fleet'],
  },
  {
    id: 'dept-5',
    name: 'General Internal Medicine & Diabetes',
    code: 'GENM',
    headDoctor: 'Dr. Sunita Kulkarni, MD',
    opdRoom: 'OPD-108',
    totalBeds: 60,
    description: 'Holistic treatment for metabolic disorders, diabetes management, infectious diseases, and executive health checkups.',
    services: ['Diabetic Care Clinic', 'Hypertension & Lipid Management', 'Infectious Disease Unit', 'Executive Health Screenings', 'Geriatric Wellness'],
  },
  {
    id: 'dept-6',
    name: 'Pediatrics & Neonatology (NICU)',
    code: 'PEDA',
    headDoctor: 'Dr. Meera Nambiar, DCH, MD',
    opdRoom: 'OPD-301',
    totalBeds: 20,
    description: 'Level 3 NICU for premature babies, pediatric surgery, child immunization, and growth monitoring.',
    services: ['Level 3 Neonatal ICU (NICU)', 'Pediatric Surgery', 'Child Immunization Schedule', 'Developmental Pediatrics', 'Pediatric Emergency'],
  },
  {
    id: 'dept-7',
    name: 'Gastroenterology & Hepatology',
    code: 'GAST',
    headDoctor: 'Dr. Srinivasulu M, DM (Gastro)',
    opdRoom: 'OPD-205',
    totalBeds: 25,
    description: 'Advanced endoscopy, colonoscopy, ERCP, liver transplantation clinic, and IBD treatment.',
    services: ['Diagnostic & Therapeutic Endoscopy', 'Colonoscopy & Polypectomy', 'ERCP Bile Duct Procedures', 'Liver Cirrhosis Care', 'IBD Clinic'],
  },
  {
    id: 'dept-8',
    name: 'Nephrology & Dialysis Unit',
    code: 'NEPH',
    headDoctor: 'Dr. Pradeep V, DM (Nephro)',
    opdRoom: 'OPD-208',
    totalBeds: 30,
    description: '24/7 hemodialysis, peritoneal dialysis, kidney transplantation, and hypertension management.',
    services: ['24/7 Hemodialysis Unit', 'SLED & CRRT for ICU Patients', 'Kidney Transplant Clinic', 'CKD Management', 'Renal Biopsy'],
  },
];

export const mockDoctors: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Vikram Reddy',
    qualification: 'MD, DM (Cardiology), FACC',
    departmentName: 'Cardiology & Cardiac Surgery',
    specialization: 'Interventional Cardiologist',
    consultationFee: 500,
    premiumFee: 750,
    availabilityDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    workingHours: '09:00 AM - 04:30 PM',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80',
    rating: 4.9,
    experienceYears: 18,
  },
  {
    id: 'doc-2',
    name: 'Dr. Ananya Swaminathan',
    qualification: 'MS, M.Ch (Neurosurgery)',
    departmentName: 'Neurology & Neurosurgery',
    specialization: 'Brain & Spine Surgeon',
    consultationFee: 600,
    premiumFee: 850,
    availabilityDays: ['Mon', 'Wed', 'Thu', 'Fri'],
    workingHours: '10:00 AM - 05:00 PM',
    image: 'https://images.unsplash.com/photo-1594824813566-88855ce78961?w=300&auto=format&fit=crop&q=80',
    rating: 4.95,
    experienceYears: 14,
  },
  {
    id: 'doc-3',
    name: 'Dr. Rajeshwar Rao',
    qualification: 'MS (Ortho), Fellowship UK',
    departmentName: 'Orthopedics & Joint Replacement',
    specialization: 'Robotic Knee & Hip Specialist',
    consultationFee: 400,
    premiumFee: 600,
    availabilityDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    workingHours: '09:30 AM - 03:30 PM',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80',
    rating: 4.8,
    experienceYears: 16,
  },
  {
    id: 'doc-4',
    name: 'Dr. Sameer Khan',
    qualification: 'MD (Emergency Med), MEM',
    departmentName: 'Emergency & Trauma Resuscitation',
    specialization: 'Trauma & Resuscitation Lead',
    consultationFee: 300,
    premiumFee: 500,
    availabilityDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    workingHours: '24/7 Shift Rotation',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80',
    rating: 4.85,
    experienceYears: 11,
  },
  {
    id: 'doc-5',
    name: 'Dr. Sunita Kulkarni',
    qualification: 'MD (Gen Med), DNB',
    departmentName: 'General Internal Medicine & Diabetes',
    specialization: 'Diabetology & Metabolic Disorders',
    consultationFee: 350,
    premiumFee: 500,
    availabilityDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    workingHours: '08:30 AM - 02:00 PM',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80',
    rating: 4.75,
    experienceYears: 12,
  },
];

export const mockHealthPackages: HealthPackage[] = [
  {
    id: 'pkg-1',
    title: 'Executive Master Health Checkup',
    price: 4999,
    originalPrice: 9500,
    recommendedFor: 'Men & Women (Age 35+)',
    isPopular: true,
    features: [
      'Complete Blood Count (CBC) with ESR (24 Tests)',
      'Lipid Profile & Cardiac Risk Markers (8 Tests)',
      'Liver Function Test LFT (11 Tests)',
      'Kidney Function Test KFT (8 Tests)',
      'HBA1C & Fasting Blood Sugar',
      'Digital Chest X-Ray & ECG',
      'Ultrasound Abdomen & Pelvis Screening',
      'Senior Doctor Consultation & Dietetics Plan',
    ],
  },
  {
    id: 'pkg-2',
    title: 'Comprehensive Cardiac Health Shield',
    price: 6499,
    originalPrice: 12000,
    recommendedFor: 'Patients with High BP, Cholesterol, Diabetes',
    isPopular: false,
    features: [
      'Treadmill Stress Test (TMT) / 2D Echocardiography',
      'Hs-CRP & High Sensitivity Cardiac Markers',
      'Complete Lipid & Triglyceride Panel',
      'Carotid Doppler Ultrasound Screening',
      'Homocysteine & Vitamin D3 Levels',
      'Interventional Cardiologist Review & Counseling',
    ],
  },
  {
    id: 'pkg-3',
    title: 'Senior Citizen Comprehensive Care',
    price: 3999,
    originalPrice: 7500,
    recommendedFor: 'Seniors (Age 60+)',
    isPopular: false,
    features: [
      'Bone Mineral Density (BMD) Dexa Scan',
      'Vitamin D3 & Vitamin B12 Levels',
      'Thyroid Profile (T3, T4, TSH)',
      'Urine Microalbumin & Kidney Screening',
      'Eye & Audiometry Screening Support',
      'Geriatric Specialist Consultation',
    ],
  },
  {
    id: 'pkg-4',
    title: 'Women Comprehensive Wellness Package',
    price: 4499,
    originalPrice: 8500,
    recommendedFor: 'Women (Age 25+)',
    isPopular: true,
    features: [
      'Pap Smear Screening & Pelvic Ultrasound',
      'Mammography / Breast Ultrasound Screening',
      'Complete Hormonal Profile (TSH, Prolactin, FSH)',
      'Iron Deficiency & Anemia Screen (Ferritin)',
      'Calcium & Vitamin D3 Screening',
      'Senior Gynaecologist Consultation',
    ],
  },
  {
    id: 'pkg-5',
    title: 'Diabetic Care & Metabolic Shield',
    price: 2999,
    originalPrice: 5500,
    recommendedFor: 'Diabetic & Pre-diabetic Patients',
    isPopular: false,
    features: [
      'HBA1C Glycated Hemoglobin & Average Blood Glucose',
      'Fasting & Post-Prandial Blood Sugar',
      'Urine Microalbumin & Renal Function Panel',
      'Diabetic Foot Neuropathy Screening',
      'Fundus Eye Screening for Retinopathy',
      'Diabetologist & Clinical Nutritionist Review',
    ],
  },
  {
    id: 'pkg-6',
    title: 'Full Body Comprehensive Preventive Cancer Screening',
    price: 8999,
    originalPrice: 16500,
    recommendedFor: 'Adults with Family History of Oncology',
    isPopular: false,
    features: [
      'Tumor Markers (PSA / CA-125 / CEA / AFP)',
      'Low Dose Whole Body CT Screening',
      'Whole Abdomen Ultrasound Screening',
      'Complete Hematology & Peripheral Smear',
      'Stool Occult Blood Screening',
      'Oncology Specialist Consultation',
    ],
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: 'blog-1',
    title: 'Recognizing Early Warning Signs of Heart Attack: Minutes Save Muscles',
    category: 'Cardiology',
    author: 'Dr. Vikram Reddy, MD, DM',
    date: '2026-07-20',
    excerpt: 'Understanding atypical chest discomfort, diaphoresis, and shortness of breath can dramatically reduce myocardial infarction damage.',
    content: 'Chest pain is not the only indicator of an impending heart attack...',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop&q=80',
    seoTitle: 'Early Heart Attack Symptoms & Cardiac Care | Bhaskar Reddy Hospital',
    seoDescription: 'Learn early warning signs of heart attack from Chief Cardiologist Dr. Vikram Reddy.',
    status: 'Published',
  },
  {
    id: 'blog-2',
    title: 'Robotic Total Knee Replacement: Faster Recovery & Sub-Millimeter Accuracy',
    category: 'Orthopedics',
    author: 'Dr. Rajeshwar Rao, MS (Ortho)',
    date: '2026-07-18',
    excerpt: 'How 4th generation robotic arm precision enables patients to walk pain-free within 24 hours of knee replacement surgery.',
    content: 'Robotic joint replacement surgery represents a massive leap forward in orthopedics...',
    image: 'https://images.unsplash.com/photo-1551076805-e1869033e561?w=600&auto=format&fit=crop&q=80',
    seoTitle: 'Robotic Knee Surgery Hyderabad | Bhaskar Reddy Hospital',
    seoDescription: 'Explore robotic joint replacement advantages with Dr. Rajeshwar Rao.',
    status: 'Published',
  },
];

export const mockGalleryItems: GalleryItem[] = [
  { id: 'g-1', title: 'Ultra-Modern Hybrid Operation Theatre', category: 'Operation Theatre', image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&auto=format&fit=crop&q=80', description: 'HEPA laminar airflow 4th Gen OT suite' },
  { id: 'g-2', title: 'Cardiac Intensive Care Unit (ICU)', category: 'ICU & Rooms', image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600&auto=format&fit=crop&q=80', description: 'Central telemetry 1:1 nursing monitoring' },
  { id: 'g-3', title: 'Deluxe Private Patient Suite', category: 'ICU & Rooms', image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?w=600&auto=format&fit=crop&q=80', description: 'Spacious room with motorized bed & recliner' },
  { id: 'g-4', title: '128-Slice Low Dose CT Scanner', category: 'Diagnostics', image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=600&auto=format&fit=crop&q=80', description: 'High speed cardiovascular imaging' },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: 'test-1',
    patientName: 'Prabhakar Rao',
    age: 58,
    treatment: 'Robotic Knee Replacement',
    doctorName: 'Dr. Rajeshwar Rao',
    rating: 5,
    reviewText: 'I was unable to walk due to severe osteoarthritis. After robotic knee replacement at Bhaskar Reddy Hospital, I was walking pain-free on the 2nd day!',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'test-2',
    patientName: 'Sunita Sharma',
    age: 46,
    treatment: 'Emergency Stenting',
    doctorName: 'Dr. Vikram Reddy',
    rating: 5,
    reviewText: 'When my husband had severe chest pain at midnight, the Emergency Triage and Cath Lab team performed angioplasty within 30 minutes. Saved his life!',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
];

export const mockContactInquiries: ContactInquiry[] = [
  {
    id: 'inq-1',
    name: 'Anand Kumar',
    phone: '+91 98480 77112',
    email: 'anand.k@gmail.com',
    subject: 'Inquiry for Cardiac Health Package',
    message: 'I want to book an Executive Cardiac Health Checkup for my parents. Please call back.',
    date: '2026-07-24 09:15',
    status: 'New Inquiry',
  },
];

export const mockAppointments: OnlineAppointment[] = [
  {
    id: 'apt-1',
    patientName: 'Kavitha Venkatram',
    patientPhone: '+91 98490 12345',
    patientAge: 48,
    patientGender: 'Female',
    doctorName: 'Dr. Vikram Reddy',
    departmentName: 'Cardiology & Cardiac Surgery',
    appointmentDate: '2026-07-25',
    appointmentTime: '10:00 AM',
    model: 'Premium Slot',
    fee: 750,
    status: 'Confirmed',
  },
];
