import type {
  Doctor,
  Department,
  HealthPackage,
  BlogPost,
  GalleryItem,
  Testimonial,
  ContactInquiry,
  OnlineAppointment,
} from './types';

export const mockDepartments: Department[] = [
  {
    id: 'dept-1',
    name: 'Obstetrics & Gynecology (Women Health)',
    code: 'OBGY',
    headDoctor: 'Dr. Madhu Latha Marreddy, MD, DGO',
    opdRoom: 'OPD-102',
    totalBeds: 40,
    description: 'Specialized high-risk pregnancy care, laparoscopic gynecological surgery, painless delivery, and fetal medicine.',
    services: ['High-Risk Pregnancy Care', 'Laparoscopic Hysterectomy', 'Painless Delivery (Epidural)', 'Infertility Evaluation', 'Fetal Ultrasound Monitoring'],
  },
  {
    id: 'dept-2',
    name: 'Cardiology & Interventional Care',
    code: 'CARD',
    headDoctor: 'Dr. Vikram Reddy, MD, DM',
    opdRoom: 'OPD-101',
    totalBeds: 45,
    description: 'Comprehensive 24/7 cardiac emergency care, interventional cardiology, TAVI, and 24-hour Cath Lab angioplasty.',
    services: ['24/7 Cath Lab & Angioplasty', 'Coronary Artery Bypass (CABG)', 'Pacemaker Implantation', '3D Echocardiography', 'Heart Failure Clinic'],
  },
  {
    id: 'dept-3',
    name: 'Orthopedics & Joint Replacement',
    code: 'ORTH',
    headDoctor: 'Dr. Rajeshwar Rao, MS (Ortho)',
    opdRoom: 'OPD-202',
    totalBeds: 50,
    description: 'Robotic knee and hip replacement, complex trauma surgery, sports medicine, and spine alignment.',
    services: ['Robotic Total Knee Replacement', 'Hip Resurfacing & Revision', 'Arthroscopic Ligament Repair', 'Polytrauma Care', 'Physiotherapy Suite'],
  },
  {
    id: 'dept-4',
    name: 'Emergency & Trauma Resuscitation',
    code: 'EMER',
    headDoctor: 'Dr. Sameer Khan, MD (EM)',
    opdRoom: 'EMR-BAY-01',
    totalBeds: 25,
    description: 'Round-the-clock level 1 trauma resuscitation in Pogathota Nellore, cardiac emergency bay, and ALS ambulance fleet.',
    services: ['Trauma Resuscitation', 'Advanced Ventilator Support', 'Poison & Toxicology Care', 'Medico-Legal Registration', 'ALS Ambulance Fleet'],
  },
  {
    id: 'dept-5',
    name: 'General Internal Medicine & Diabetes',
    code: 'GENM',
    headDoctor: 'Dr. Sunita Kulkarni, MD',
    opdRoom: 'OPD-108',
    totalBeds: 60,
    description: 'Holistic treatment for metabolic disorders, diabetes management, infectious diseases, and executive health checkups.',
    services: ['Diabetic Care Clinic', 'Hypertension & Lipid Management', 'Infectious Disease Unit', 'Executive Health Screenings', 'Geriatric Wellness'],
  },
  {
    id: 'dept-6',
    name: 'Pediatrics & Neonatology (NICU)',
    code: 'PEDA',
    headDoctor: 'Dr. Meera Nambiar, DCH, MD',
    opdRoom: 'OPD-301',
    totalBeds: 20,
    description: 'Level 3 NICU for premature babies, pediatric surgery, child immunization, and growth monitoring.',
    services: ['Level 3 Neonatal ICU (NICU)', 'Pediatric Surgery', 'Child Immunization Schedule', 'Developmental Pediatrics', 'Pediatric Emergency'],
  },
];

export const mockDoctors: Doctor[] = [
  {
    id: 'doc-0',
    name: 'Dr. Madhu Latha Marreddy',
    qualification: 'MD, DGO (Obstetrics & Gynaecology)',
    departmentName: 'Obstetrics & Gynecology (Women Health)',
    specialization: 'High-Risk Pregnancy & Laparoscopic Surgeon',
    consultationFee: 450,
    premiumFee: 650,
    availabilityDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    workingHours: '09:30 AM - 05:00 PM',
    image: 'https://images.unsplash.com/photo-1594824813566-88855ce78961?w=300&auto=format&fit=crop&q=80',
    rating: 4.95,
    experienceYears: 19,
  },
  {
    id: 'doc-1',
    name: 'Dr. Vikram Reddy',
    qualification: 'MD, DM (Cardiology), FACC',
    departmentName: 'Cardiology & Interventional Care',
    specialization: 'Interventional Cardiologist',
    consultationFee: 500,
    premiumFee: 750,
    availabilityDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    workingHours: '09:00 AM - 04:30 PM',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80',
    rating: 4.9,
    experienceYears: 18,
  },
  {
    id: 'doc-3',
    name: 'Dr. Rajeshwar Rao',
    qualification: 'MS (Ortho), Fellowship UK',
    departmentName: 'Orthopedics & Joint Replacement',
    specialization: 'Robotic Knee & Hip Specialist',
    consultationFee: 400,
    premiumFee: 600,
    availabilityDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    workingHours: '09:30 AM - 03:30 PM',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80',
    rating: 4.8,
    experienceYears: 16,
  },
];

export const mockHealthPackages: HealthPackage[] = [
  {
    id: 'pkg-1',
    title: 'Executive Master Health Checkup',
    price: 4999,
    originalPrice: 9500,
    recommendedFor: 'Men & Women (Age 35+)',
    isPopular: true,
    features: [
      'Complete Blood Count (CBC) with ESR (24 Tests)',
      'Lipid Profile & Cardiac Risk Markers (8 Tests)',
      'Liver Function Test LFT (11 Tests)',
      'Kidney Function Test KFT (8 Tests)',
      'HBA1C & Fasting Blood Sugar',
      'Digital Chest X-Ray & ECG',
      'Ultrasound Abdomen & Pelvis Screening',
      'Senior Doctor Consultation & Dietetics Plan',
    ],
  },
  {
    id: 'pkg-2',
    title: 'Comprehensive Cardiac Health Shield',
    price: 6499,
    originalPrice: 12000,
    recommendedFor: 'Patients with High BP, Cholesterol, Diabetes',
    isPopular: false,
    features: [
      'Treadmill Stress Test (TMT) / 2D Echocardiography',
      'Hs-CRP & High Sensitivity Cardiac Markers',
      'Complete Lipid & Triglyceride Panel',
      'Carotid Doppler Ultrasound Screening',
      'Homocysteine & Vitamin D3 Levels',
      'Interventional Cardiologist Review & Counseling',
    ],
  },
  {
    id: 'pkg-3',
    title: 'Women Comprehensive Maternity & Gynec Package',
    price: 4499,
    originalPrice: 8500,
    recommendedFor: 'Women & Expectant Mothers',
    isPopular: true,
    features: [
      'Pap Smear Screening & Pelvic Ultrasound',
      'High-Resolution Fetal Well-being Scan',
      'Complete Hormonal Profile (TSH, Prolactin, FSH)',
      'Iron Deficiency & Anemia Screen (Ferritin)',
      'Calcium & Vitamin D3 Screening',
      'Dr. Madhu Latha Marreddy Consultation',
    ],
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: 'blog-1',
    title: 'Recognizing Early Warning Signs of Heart Attack: Minutes Save Muscles',
    category: 'Cardiology',
    author: 'Dr. Vikram Reddy, MD, DM',
    date: '2026-07-20',
    excerpt: 'Understanding atypical chest discomfort, diaphoresis, and shortness of breath can dramatically reduce myocardial infarction damage.',
    content: 'Chest pain is not the only indicator of an impending heart attack...',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop&q=80',
    seoTitle: 'Early Heart Attack Symptoms & Cardiac Care | Bhaskar Reddy Hospital Nellore',
    seoDescription: 'Learn early warning signs of heart attack from Chief Cardiologist Dr. Vikram Reddy.',
    status: 'Published',
  },
];

export const mockGalleryItems: GalleryItem[] = [
  { id: 'g-1', title: 'Ultra-Modern Operation Theatre', category: 'Operation Theatre', image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&auto=format&fit=crop&q=80', description: 'Laminar airflow surgical suite at Pogathota Nellore' },
  { id: 'g-2', title: 'Cardiac Intensive Care Unit (ICU)', category: 'ICU & Rooms', image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600&auto=format&fit=crop&q=80', description: '24/7 critical care monitoring' },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: 'test-1',
    patientName: 'Kavitha Devi',
    age: 32,
    treatment: 'Laparoscopic Surgery',
    doctorName: 'Dr. Madhu Latha Marreddy',
    rating: 5,
    reviewText: 'Dr. Madhu Latha ma’am provided exceptional care during my high-risk pregnancy and delivery at Pogathota Nellore branch. Extremely satisfied with nursing support!',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
];

export const mockContactInquiries: ContactInquiry[] = [
  {
    id: 'inq-1',
    name: 'Suresh Babu',
    phone: '+91 98480 11223',
    email: 'suresh.babu@gmail.com',
    subject: 'Maternity Package Inquiry - Nellore',
    message: 'Requesting consultation details for maternity package at Pogathota branch.',
    date: '2026-07-24 10:30',
    status: 'New Inquiry',
  },
];

export const mockAppointments: OnlineAppointment[] = [
  {
    id: 'apt-1',
    patientName: 'Venkat Rao',
    patientPhone: '+91 98490 55443',
    patientAge: 42,
    patientGender: 'Male',
    doctorName: 'Dr. Madhu Latha Marreddy',
    departmentName: 'Obstetrics & Gynecology (Women Health)',
    appointmentDate: '2026-07-25',
    appointmentTime: '10:30 AM',
    model: 'Premium Slot',
    fee: 650,
    status: 'Confirmed',
  },
];
